language: python
python:
  - "3.8"

services:
  - docker

#run before it executes any of the automation commands
before_script: pip install docker-compose


script:
  - docker-compose run app sh -c "python manage.py test && flake8"